# Use root/example as user/password credentials
version: '3.1'

services:
  reservation-db:
    platform: linux/amd64
    image: hub.oliveyoung.co.kr/reservation-test-device/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'olive_reservation'
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'olive'
      MYSQL_PASSWORD: 'olive_password'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
  
  reservation-adminer:
    image: hub.oliveyoung.co.kr/reservation-test-device/adminer
    restart: always
    ports:
      - 8000:8080
  
  reservation-node:
    image: hub.oliveyoung.co.kr/reservation-test-device/node-alpine-16
    working_dir: /app
    command: npm start
    volumes:
      - ../app:/app
    ports:
      - 8080:8080
    depends_on:
      reservation-db:
        condition: service_healthy
    links:
      - reservation-db
